title: YOUR TITLE
description: YOUR DESCRIPTION
theme: just-the-docs

url: https://Ymauvaisetroupe.github.io/just-the-docs-sample

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/mauvaisetroupe/just-the-docs-sample
